### ISSUE TITLE
Jupyter notebook - kernel crashes when importing anndata2ri

### ISSUE THREAD

**Issue by Gokhan169** [theislab/anndata2ri#158]
Hi,

It seems that I am unable to import anndata2ri. Whenever I tried in the jupyter notebook, I get the following error. I would be really glad if you can help me with this issue. Thanks.

Kernel Restarting
The kernel for Desktop/Merfish analysis/Untitled8.ipynb appears to have died. It will restart automatically.

**Comment by flying-sheep** [comment]
Hi, please give me something to work with, like a traceback.

You could e.g. try setting the environment variable `PYTHONFAULTHANDLER=1` before starting jupyter lab.

I’ll close this since it has no actionable information, but please comment if you have anything workable and I’ll reopen

**Comment by Urja25** [comment]
I am facing the same problem. How do I provide you the traceback? (sorry I'm quite new to python)
