### ISSUE TITLE
SyntaxError: future_fstrings

### ISSUE THREAD

**Issue by aopisco** [theislab/anndata2ri#22]
`import anndata2ri`

SyntaxError: unknown encoding for '/home/ubuntu/anaconda3/lib/python3.6/site-packages/get_version.py': future_fstrings

**Comment by aopisco** [comment]
there shouldn't be problems with future_fstrings in python 3.6 (https://github.com/asottile/future-fstrings/issues/11) but I can't import this package

**Comment by flying-sheep** [comment]
Well, that seems like a problem with `future-fstrings` or your setup, not `get_version`, and certainly not `anndata2ri`.
