### ISSUE TITLE
Error in installing anndata2ri

### ISSUE THREAD

**Issue by aditisk** [theislab/anndata2ri#25]

**Comment by aditisk** [comment]
I tried downloading directly from Github as well as the local download but I am getting this error when I run the install command:

(base) CCBR-KULKARiMAC:anndata2ri-master kulkarnia2$ pip install .
Processing /Users/kulkarnia2/Downloads/anndata2ri-master
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/kulkarnia2/miniconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/56/g1b462hs0d3816ktcj6twm8hmsw5ch/T/pip-req-build-vlsj6398/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/56/g1b462hs0d3816ktcj6twm8hmsw5ch/T/pip-req-build-vlsj6398/

Could you please help me fix this ? Thanks.

**Comment by aditisk** [comment]
It works on my macbook, not sure why it isn't working on the Mac desktop.

**Comment by flying-sheep** [comment]
You need to upgrade pip to 19.0 or later
