### ISSUE TITLE
Udate: `np.matrix` conversion (issue #24)

### ISSUE THREAD

**Issue by mumichae** [theislab/anndata2ri#26]
## Update to #24

Issued the problem at rpy2 (https://bitbucket.org/rpy2/rpy2/issues/576/incorrect-conversion-of-npmatrix) The best fix would be to use `np.array` instead of `np.matrix` seeing as the latter is no longer recommended
```
matrix(data, dtype=None, copy=True)

.. note:: It is no longer recommended to use this class, even for linear
          algebra. Instead use regular arrays. The class may be removed
          in the future.
```

**Comment by flying-sheep** [comment]
Yes, I’m aware. Why did you file this as an issue? I’ve known this for a long time and never use `numpy.matrix`, and `anndata2ri` doesn’t explicity handle the class or create an instance of it.
