### ISSUE TITLE
Unable to install anndata2ri

### ISSUE THREAD

**Issue by heeroena** [theislab/anndata2ri#27]
Hi Admin,
I am trying to install anndata2ri in linux but I get the error of setup.py file being missing.

regards

**Comment by flying-sheep** [comment]
You didn’t follow the installation instructions (hint: which version of pip do you have installed?)

**Comment by heeroena** [comment]
pip 19.2.2

**Comment by flying-sheep** [comment]
Well, when the error said “setup.py is missing” then you had pip < 19.0 at that point. If the error is something during loading/installing a package then it’s that package (e.g. rpy2). If it’s something else, then I can help you.
