### ISSUE TITLE
Seurat package won't load for anndata2ri conversion? 

### ISSUE THREAD

**Issue by Seandelao** [theislab/anndata2ri#29]
Hello, 

I am following the tutorial for conversion of a Seurat object into an AnnData object for further analysis in Scanpy. However, when I try to run the Jupyter Notebook cell: 

%%R
suppressPackageStartupMessages(library(Seurat))

I get the error:

Error in library(Seurat) : there is no package called ‘Seurat’
Calls: <Anonymous> ... suppressPackageStartupMessages -> withCallingHandlers -> library

I definitely have Seurat installed in R, so I'm not sure what is going on. Am I doing something wrong?

**Comment by flying-sheep** [comment]
anndata2ri is just the conversion layer between some Python and R classes. The package providing the actual R-Python integration is [rpy2](https://rpy2.bitbucket.io/). Please report problems there if they happen before anndata2ri comes into play.

**Comment by r-mvl** [comment]
I have been having similar issue. As far as I can tell this tool is to facilitate interactions between seurat and scanpy. Howver, people who have been using seurat are likely to be more comfortable using R than python. There seem to be some conflicts with latests version of seurat/reticulate and rpy2. I have no idea how to circumvent this problem, but it would be great if developers here could look at this issue.

**Comment by flying-sheep** [comment]
General tip: If you have multiple R installations, you need to install Seurat in the package library for the one that rpy2 is linked against. I think you should find that using `from rpy2.rinterface_lib.openrlib import R_HOME`. For me that’s `/usr/lib64/R`, so the R version Seurat has to be installed in has to be `/usr/lib64/R/bin/R`. If that doesn’t help, check that the `.libPaths()` from R and from rpy2 match.

If this doesn’t help you, please be aware you’re asking for help regarding Seurat’s interaction with rpy2, so your best bet is to ask in the Seurat or rpy2 issue tracker. Post all information you discovered with the instructions above there, and please post a comment here with a link to the issue you opened there.
