### ISSUE TITLE
add to bioconda

### ISSUE THREAD

**Issue by grst** [theislab/anndata2ri#30]
Would be great to have this available on bioconda. 
I can take care of that if you create a release of the current version (0.1 seems to be quite outdated). 

Cheers, 
Gregor

**Comment by grst** [comment]
now available: https://anaconda.org/bioconda/anndata2ri

Cheers, 
G.

**Comment by rowanworth** [comment]
Hm, bioconda/anndata2ri relies on rpy2[version='>=3.0.1'] and yet the latest version of rpy2 in the bioconda channel appears to be v2.7.8: https://anaconda.org/bioconda/rpy2

Am I missing something? Is this supposed to be used in conjunction with another channel, or is rpy2 expected to be available already in the environment? My R version should be sufficient (4.0.2) and yet I get a failure with `conda create -p /tmp/conda_anndata2ri -c bioconda anndata2ri`:

```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - anndata2ri
  - get_version
  - anndata2ri
  - rpy2[version='>=3.0.1']

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
```

This was with an older anaconda release (conda 4.5.4), however updating to the latest (conda 4.12.0) offers an inscrutable error with no details at all:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                               failed                                                                                                   

UnsatisfiableError: 
```

(also tried miniconda but that had a different complaint unrelated to anndata2ri)

I realise this is an old issue but the version='>=3.0.1' restriction seems to have been in place from the start

**Comment by grst** [comment]
>  Is this supposed to be used in conjunction with another channel,

Bioconda is *always* supposed to be used together with the `conda-forge` channel, as shown in the [bioconda docs](https://bioconda.github.io/#usage). Please note that the order of the channels matter, i.e. the `conda-forge` channel must have higher priority than bioconda.

**Comment by rowanworth** [comment]
Thank you! Love it when there's a simple solution, appreciate you spelling it out for me.
