### ISSUE TITLE
Support converting factors in obs/var to pd.Series with CategoricalDtype

### ISSUE THREAD

**Issue by apblair** [theislab/anndata2ri#39]
First, thanks for developing this converter! 

The wiki section on 'Usage from IPython' on converting to a SingleCellExperiment back to an anndata object should be:

```r
%%R -o adata_allen
data(adata_paul, package = 'scRNAseq')  # conversion works without this line
adata_allen <- as(adata_paul, 'SingleCellExperiment')
```

The conversion also removes the cluster/celltype naming in the original obs column `'paul15_clusters'`.

Also, the scanpy/seurat tutorial link does not work when you use:

```r
as.SingleCellExperiment(adata)
```

instead of 

```r
as(adata, 'SingleCellExperiment')
```

**Comment by flying-sheep** [comment]
Hi! Thanks for the praise!

First of all, I changed your post to use proper GitHub formatting. Please hit the edit button on your post to see how to do code blocks on GitHub for next time.

About your issues:

1. You misunderstood what that README (not wiki) says. `data(allen, package = 'scRNAseq')` doesn’t convert an existing dataset or so, it loads a completely new dataset called “allen” from the `scRNAseq` package and saves it as the variable `allen`.

  For me, `paul_15` converts back and forth perfectly:

  ```py
  adata = sc.datasets.paul15()
  ```

  ```r
  %%R -i adata -o adata2
  adata2 <- adata
  ```

  ```py
  adata2
  # AnnData object with n_obs × n_vars = 2730 × 3451 
  #   obs: 'paul15_clusters'
  #   uns: 'iroot'
  ```

2. What do you mean by “does not work”. I need a traceback and/or a detailed description.

**Comment by apblair** [comment]
Thanks for showing me how to make code blocks, much appreciated! :)

Following up on your comments:

1. In the example I meant to outline, the `paul_15` adata obs column 'paul15_clusters' has a vector of what I assume are cluster by cell type labels but when you convert it to a SingleCellExperiment object and back to an adata object there are only cluster labels. For example, the adata object before conversion shows '7MEP' as the first item in the 'paul_15_clusters' column and after the conversion to SingleCellExperiment and back to adata I only see '7'.

2. Please disregard, this was not an error. I did not have the Seurat library loaded.

**Comment by flying-sheep** [comment]
You’re right, categorical data types don’t survive the roundtrip.

**Comment by LuckyMD** [comment]
Is this fixed in the meanwhile? I'm also hitting the same issue atm.
