### ISSUE TITLE
Problems with Seurat

### ISSUE THREAD

**Issue by sergiopolid** [theislab/anndata2ri#40]
I have problems when trying to initiate Seurat under IPython: 

%%R 
    ...: library(Seurat)
    ...:  
    ...:                                                                        
Segmentation fault: 11

Any clues?

**Comment by sergiopolid** [comment]
This happens with the computer cluster (w/150GB) and also in a regular laptop

**Comment by flying-sheep** [comment]
Anndata2ri isn’t involved here at all, right?

I guess you should report this to rpy2 (or maybe Seurat or Python itself), and nobody will ever be able to help you if you don’t give people the versions of everything involved. If nobody can reproduce it, they’ll also need you to run Python using valgrind to debug this.
