### ISSUE TITLE
bioconda version out of date

### ISSUE THREAD

**Issue by scottgigante-immunai** [theislab/anndata2ri#86]
anndata2ri is at 1.1 on PyPi and 1.0.6 on bioconda. In theory, bioconda should automatically update. Any ideas why it hasn't?

**Comment by scottgigante-immunai** [comment]
Just saw https://github.com/bioconda/bioconda-recipes/pull/35607 . Looks like it was ready to merge 5 days ago but the bot didn't merge the PR?

**Comment by scottgigante-immunai** [comment]
cc @daler @flying-sheep

**Comment by daler** [comment]
Just gave the bot a nudge -- for some reason it didn't trigger the first time.
