### ISSUE TITLE
Exactly how to use LocalConverter to convert from AnnData to SCE within a normal Python script

### ISSUE THREAD

**Issue by EdwardAgboraw** [theislab/anndata2ri#90]
I'm trying to use anndata2ri as a part of a normal Python script, but have a quick question.

In this example line of code:

```py
with localconverter(anndata2ri.converter):
    adata = r('as(some_data, "SingleCellExperiment")')
```

Where does the "some_data" object come from? I assume its meant to be the AnnData object being converted, but how exactly should it be created? If its meant to be the AnnData file represented as an R object, how would I go about doing that? I've tried replacing "some_data" with the path to my AnnData h5ad file, but that results in an error. 

And is there a tutorial/example script showing how anndata2ri is meant to be used within normal Python scripts? Most of the resources I've been able to find so far are focused on Jupyter notebooks.

**Comment by flying-sheep** [comment]
That example is for R→Python. `some_data` is an R object that can be converted to `SingleCellExperiment` (SCE), e.g. an `ExpressionSet` or so. As `anndata2ri` can only convert SCEs to `AnnData`, in this example we convert that object first to a SCE (without leaving R), then use `anndata2ri` to convert the SCE to a Python `AnnData` object at the R→Python boundary.

For usage from Python, see https://github.com/theislab/anndata2ri#usage-from-python

**Comment by EdwardAgboraw** [comment]
Thanks for the quick reply!
That does work me. Initially I did run into another error:

` Error in Matrix::sparseMatrix(..., x = conv_data(x), dims = as.integer(dims),  : 
  unused argument (repr = "C")
`

But simply converting the count matrix in my anndata object (Adata.X) to a dense matrix was enough to solve that problem (though I am curious what caused it) - the conversion runs smoothly now.

Thanks again for your help!
