### ISSUE TITLE
When I used the anndata2ri and rpy2, the error happened. 

### ISSUE THREAD

**Issue by melancholy12** [theislab/anndata2ri#94]
![image](https://user-images.githubusercontent.com/97800939/196549399-28f63c41-bcff-4594-8bbf-f72f5d467c66.png)

**Comment by flying-sheep** [comment]
To fix errors like this, install the package in question (here [S4Vectors](https://bioconductor.org/packages/release/bioc/html/S4Vectors.html)) into your R environment.

**Comment by nilchia** [comment]
if you have S4Vectors and you still get this error, make sure R and Python are using the same R Environment. 

```Python
import rpy2.robjects as to
ro.r('.libPaths()')
```
should match `.libPaths()` in the R console.
